use_frameworks!

platform :ios, '10.0'

target 'Go23WalletGoBack_Example' do
  pod 'Go23WalletGoBack', :path => '../'

  target 'Go23WalletGoBack_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
